version: '3'

services:
  httpd:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
  db:
    image: postgres:15.2
    restart: unless-stopped
    env_file:
        - ../backend/.env
    ports:
        - '5432:5432'
    volumes:
        - db-data:/var/lib/postgresql/data  
volumes:
    db-data: